### ISSUE TITLE
Consider converting to JHipster module

### ISSUE THREAD

**Issue by murdos** [merlinofcha0s/generator-jhipster-flutter#1]
I discovered this jhispter blueprint by chance, and checked quickly the code to see how it was working (note: I've not tried it yet).

I see you're overriding the client part of JHipster (although your subgenerator is named "app"...), so this does not allow user to have both a Flutter client and a web client (Angular, React, ...).
If you switch to a JHipster module, you might provide additional feature to a JHipster application without user having to make a choice between mobile front-end and web front-end.

Note: a JHipster user can disable client side when generating a monolith application, using the `--skip-client` flag

**Comment by merlinofcha0s** [comment]
I didn't saw the real difference between blueprints and module. But yes you're right it will be more flexible as a module.

I'll try to convert it, thanks for the feedback 😄
