### ISSUE TITLE
Can't Generate Entities

### ISSUE THREAD

**Issue by ahmedcatch** [merlinofcha0s/generator-jhipster-flutter#40]
<img width="415" alt="Screen Shot 2020-10-13 at 19 46 18" src="https://user-images.githubusercontent.com/64021812/95960403-99031300-0dfb-11eb-9e9f-86b723ceece8.png">
Hi Cyril,

I am trying generate entities following your blog here
https://blog.herofactory.dev/using-the-flutter-entity-generator-jhipster/

However, I am getting an error saying it can't find a project containing the .jhipster folder where the entities. 
I have already generated the entities on the server and there is a .jhipster with JSON representations of the entities.
I tried both individual entity or all the entities.

I installed the generator from npm globally also tried to install the generator as development both the flutter generator and the parent JHipster generator. I did the proper linking. 

see the screenshot below  
<img width="1414" alt="Screen Shot 2020-10-13 at 19 23 49" src="https://user-images.githubusercontent.com/64021812/95901600-7b966080-0d8b-11eb-8562-3a81511107aa.png">
<img width="781" alt="Screen Shot 2020-10-13 at 19 40 41" src="https://user-images.githubusercontent.com/64021812/95902013-1727d100-0d8c-11eb-8f4d-f3b4cf9ccf0a.png">
...
blow is screenshot of the folder three of the 3 project, somalivisaserver is the JHipster generated project with .jhipster folder
<img width="493" alt="Screen Shot 2020-10-13 at 19 55 20" src="https://user-images.githubusercontent.com/64021812/95903540-39225300-0d8e-11eb-93fb-8c7df79138d9.png">

**Comment by merlinofcha0s** [comment]
Hi Ahmed,
Did you tried to put the path in relatives (ex : ../somalivisaserver) ?

**Comment by ahmedcatch** [comment]
Hi Cyril,

Yes, I tried both absolute and relative path referencing before, I tried again and shared a screenshot of it.  The issue is still the same. thanks
<img width="1440" alt="Screen Shot 2020-10-20 at 11 49 12" src="https://user-images.githubusercontent.com/64021812/96576897-bab43c80-12ca-11eb-82a6-6a3a13602636.png">

**Comment by merlinofcha0s** [comment]
Okay, First can you get rid of the two .yo-rc.json and .yo-repository in the somalivisamobile and remove the flutter-app folder by copying all this folder contents in the somalivisamobile folder. Then launch the generator again ?

If the first step is not working can you copy / paste the somalivisamobile folder in the folder somalivisaserver and launch the generator again.

Tell me if it's working.

**Comment by VladForUA** [comment]
I had the same error , make sure that you create flutter app in server folder .

//Creating Server

mkdir jh-server-flutter ---- ++++
cd jh-server-flutter
jhipster
./mvnw

//Create flutter in server folder

cd jh-server-flutter  --- ++++++
yo jhipster-flutter-merlin

// import-jdl  - create entities in server app


// after go to flutter folder and run

yo jhipster-flutter-merlin:entities

**Comment by merlinofcha0s** [comment]
I'll close this issue because it's old, feel free to create another one if needed
