### ISSUE TITLE
Issues when creating an entity with a multiword name

### ISSUE THREAD

**Issue by SpiralUp** [merlinofcha0s/generator-jhipster-flutter#43]
Hi Cyril,

I'm trying to generate entities with a name that consist of several words (for example CatalogItem) but getting errors in generated files.

Could you please, make following corrections:

In the file **generators/entity/index.js**:
![image](https://user-images.githubusercontent.com/1242688/97661460-ad3e4580-1a74-11eb-9ac1-a4ebb97ff275.png)

In the file **generators/entity/templates/flutter/lib/entity.model.ejs**:
![image](https://user-images.githubusercontent.com/1242688/97661538-ebd40000-1a74-11eb-93ff-4109d41399c9.png)

Best regards
Ivan

**Comment by merlinofcha0s** [comment]
Hi Ivan

Okay, I'll look into it

Regards
