### ISSUE TITLE
I cant run the generator in Jhipster V7 

### ISSUE THREAD

**Issue by AdalWay** [merlinofcha0s/generator-jhipster-flutter#51]
This generator (jhipster-flutter-merlin:app) requires yeoman-environment at least 3.0.0, current version is 2.10.3, 

I haven't been able to run the generator, I even tried reinstalling the latest version of "YO".
Note: I'm running the Jhipster V7 in Ubuntu(Linux
![Screenshot from 2021-03-23 13-46-36](https://user-images.githubusercontent.com/1254478/112193591-6b0dd000-8bde-11eb-8080-f7d34ee82efc.png)
)

**Comment by merlinofcha0s** [comment]
Can you check your version with `yo --version` and be sure that you have the right version ?

<img width="473" alt="image" src="https://user-images.githubusercontent.com/6643835/112459306-f8c3f980-8d5d-11eb-910e-d4efc4f999f7.png">

**Comment by AdalWay** [comment]
Yes I do have the 3.1.1 version installed.

**Comment by merlinofcha0s** [comment]
Can you make a `yo doctor` and `yo --version` and upload the screenshot here ?

I don't think that there are any dependencies missing / outdated on the generator.

**Comment by manikmmalhotra** [comment]
I've encountered the same issue and you can change the yeoman-generator version to "yeoman-generator": "^4.0.1" it helps for me

**Comment by AdalWay** [comment]
here is the screenshot you asked for
![Screenshot from 2021-03-28 22-43-27](https://user-images.githubusercontent.com/1254478/112780592-28e9f180-9017-11eb-8994-e035e1823d40.png)

**Comment by msgoon** [comment]
I founded the error, in V7 this method, this.getAllJhipsterConfig, need 2 params and the call was made without params i put a PR with this fix

**Comment by merlinofcha0s** [comment]
Okay I'm able to reproduce it
I'll fix it ASAP

**Comment by RickPoleshuck** [comment]
This works for me:
$ jhipster run jhipster
